$SCRIPT=~/.config/hypr/scripts/ # hyprland scripts path

# workspaces
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, S, togglespecialworkspace

# move window to workspace
bind = Super+Alt, 1, movetoworkspace, 1
bind = Super+Alt, 2, movetoworkspace, 2
bind = Super+Alt, 3, movetoworkspace, 3
bind = Super+Alt, 4, movetoworkspace, 4
bind = Super+Alt, 5, movetoworkspace, 5
bind = Super+Alt, 6, movetoworkspace, 6
bind = Super+Alt, 7, movetoworkspace, 7
bind = Super+Alt, 8, movetoworkspace, 8
bind = Super+Alt, 9, movetoworkspace, 9
bind = Super+Alt, S, movetoworkspacesilent, special

# move window to another side
bind = Super+Shift, left, movewindow, left
bind = Super+Shift, right, movewindow, right
bind = Super+Shift, up, movewindow, up
bind = Super+Shift, down, movewindow, down

# focus to another window
bind = Super, left, movefocus, left
bind = Super, right, movefocus, right
bind = Super, up, movefocus, up
bind = Super, down, movefocus, down

# move window to next/previous workspace
bind = Super+Ctrl+Shift, left, movetoworkspace, -1
bind = Super+Ctrl+Shift, right, movetoworkspace, +1

# switch to next/previous workspace
bind = Super+Ctrl, left, workspace, -1
bind = Super+Ctrl, right, workspace, +1

# resize window
binde = Super+Alt, left, resizeactive, -15 0
binde = Super+Alt, right, resizeactive, 15 0
binde = Super+Alt, up, resizeactive, 0 -15
binde = Super+Alt, down, resizeactive, 0 15

# quickshell
bind = Super, Period, exec, qs ipc call launcher emoji
bind = Super, V, exec, qs ipc call launcher clipboard
binde= , XF86Tools, exec, qs ipc call launcher toggle
bind = Super+Alt, Slash, exec, qs ipc call launcher toggle
bind = Ctrl+Alt, Delete, exec, qs ipc call sessionMenu toggle
bind = Super+Ctrl, R, exec, pkill qs;qs

# apps
bind = Super, T, exec, AyuGram
bind = Super, E, exec, nautilus
bind = Super, Return, exec, kitty
bind = Super+Ctrl, W, exec, zen-browser
bind = Ctrl+Shift, Escape, exec, missioncenter

# action with window
bind = Super, Q, killactive # close
bind = Super, F, fullscreen, 0 # fullscreen
bind = Super, D, fullscreen, 1 # maximize
bindm= Super, mouse:272, movewindow # move window by mouse
bindm= Super, mouse:273, resizewindow # resize window by mouse
bind = Super+Ctrl, Z, forcekillactive # kill
bind = Super+Alt, Space, togglefloating
bind = Super+Ctrl+Shift, Z, exec, $SCRIPT/freezeactive.sh

# zoom
binde = Super+Ctrl, Equal, exec, $SCRIPT/zoom.sh increase 0.25
binde = Super+Ctrl, Minus, exec, $SCRIPT/zoom.sh decrease 0.25
bind  = Ctrl+Super, Backslash, exec, $SCRIPT/zoom.sh reset

# screen shot/record
bind = Super+Shift, S, exec, grimblast --freeze copy area area
bind = , Print, exec, grimblast copy
bind = Super+Shift+Alt, R, exec, $SCRIPT/record.sh --fullscreen-sound
bind = Super+Alt, R, exec, $SCRIPT/record.sh --sound

# session
bind = Super+Ctrl, F, exec, sudo poweroff
bind = Super+Ctrl, S, exec, echo mem | sudo tee /sys/power/state # suspend

# display
bind = Super+Ctrl, A, exec, hyprctl dispatch dpms toggle

# media
bind  = Super, M, exec, playerctl play-pause
binde = , XF86AudioRaiseVolume, exec, flock -n /tmp/hypr_raise.lock -c "$SCRIPT/volume.sh raise 5"
binde = , XF86AudioLowerVolume, exec, flock -n /tmp/hypr_lower.lock -c "$SCRIPT/volume.sh lower 5"
bind  = , XF86AudioMute, exec, $SCRIPT/volume.sh reset # set volume to 0
bind  = , XF86AudioMicMute, exec, $SCRIPT/volume.sh mute

# misc
bind = Super+Shift, P, exec, hyprpicker -a # color picker
bind = Super, Space, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next # Switch keyboard layout
