$SCRIPT=~/.config/hypr/scripts/ # hyprland scripts path

exec-once = qs
exec-once = awww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Ice 20
exec-once = hypr-wellbeing -d
exec-once = ntfy subscribe --from-config
exec-once = $SCRIPT/battery_daemon.sh
