workspace = special:special, gapsout:25
workspace = w[1], bordersize:0
workspace = f[1], bordersize:0
windowrule = match:float 1, border_size 1
windowrule = match:class org.gnome.clocks, float on
windowrule = match:workspace special:special, border_size 1
windowrule = match:class ^(Minecraft.*)$, fullscreen 1

# term
windowrule = workspace 1, match:class kitty

# browser
windowrule = workspace 2, match:class zen 

# communication
windowrule = workspace 3, match:class ^(.*gram.desktop)$
windowrule = workspace 3, match:class vesktop

# utilities
windowrule = workspace 4, match:class org.gnome.Nautilus
windowrule = workspace 4, match:class localsend
windowrule = workspace 4, match:class org.pulseaudio.pavucontrol
windowrule = workspace 4, match:class io.missioncenter.MissionCenter
windowrule = workspace 4, match:class gpartedbin
windowrule = workspace 4, match:title Библиотека

# need in bg
windowrule = workspace 5, match:class org.qbittorrent.qBittorrent
windowrule = workspace 5, match:class hiddify

# games
windowrule = workspace 6, match:class org.vinegarhq.Sober
windowrule = workspace 6, match:class steam
windowrule = workspace 6, match:class org.freesmTeam.freesmlauncher
windowrule = workspace 6, match:class ^(Minecraft.*)$
windowrule = workspace 6, match:class gorebox.exe

# need in fullscreen
windowrule = workspace 7, match:class gimp
